#+Title: Test case
#+Date: 30 Jan 2017
#+Author: SravanthiB

* Environment

  +  OS: Windows 7, Linux
  +  Browsers: Firefox,Chrome
  +  Bandwidth : 100Mbps
  +  Hardware Configuration:8GBRAM,
  +  Processor:i5

* Objective

   + To be able to simulate the "Nuclear Magnetic Resosnace Spectrocopy and Evaulation of Simple 1H NMR Spectra of Select Organic Compounds" experiment
     
* Pre conditions

  +  Refer to first test case [[https://github.com/Virtual-Labs/physical-chemistry-iiith/blob/master/test-cases/integration-test-cases/EXPT-5/Nuclear-Magnetic-Resosnace-Spectrocopy-and-Evaulation-of-Simple-1H-NMR-Spectra-of-Select-Organic-Compounds_01_Usability_smk.org][Nuclear-Magnetic-Resosnace-Spectrocopy-and-Evaulation-of-Simple-1H-NMR-Spectra-of-Select-Organic-Compounds_01_Usability_smk.org]]

* Post conditions

  +  Nil
     
* Test Steps

  +  Click on the "Nuclear Magnetic Resosnace Spectrocopy and Evaulation of Simple 1H NMR Spectra of Select Organic Compounds" link.
  +  Check if there are any distortions, spelling mistakes and junk
     characters in the Simulation page.

* Expected result

  + The home page of "Nuclear Magnetic Resosnace Spectrocopy and Evaulation of Simple 1H NMR Spectra of Select Organic Compounds" experiment should be displayed on the screen.
  + The Home page should be present with no distortions, spelling mistakes and Junk characters.

* Review/comments
